### ISSUE TITLE
Error java.io.IOException: No space left on device 

### ISSUE THREAD

**Issue by haripriyarhp** [tabular-io/iceberg-kafka-connect#114]
Hi, 
I have the connector running on k8s. It runs fine for the initial few commits and then always fails with the below error. Setting jvmoptions to the connect did not work. Below are the parameters used 

          connector.class: io.tabular.iceberg.connect.IcebergSinkConnector
          topics: test-topic-1
          iceberg.tables: db.iceberg_connector_table
          iceberg.tables.auto-create-enabled: true
          iceberg.catalog.catalog-impl: org.apache.iceberg.aws.glue.GlueCatalog
          iceberg.catalog.warehouse: s3://bucketname/object_key
          iceberg.catalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
          iceberg.control.commit.interval-ms: 30000
          value.converter.schemas.enable: true
          key.converter: org.apache.kafka.connect.storage.StringConverter
          value.converter: io.confluent.connect.avro.AvroConverter 
          value.converter.schema.registry.url: http://localhost:8081 
          value.converter.value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

`"org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception. at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:614) at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336) at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237) at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257) at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.io.UncheckedIOException: Failed to flush row group at org.apache.iceberg.parquet.ParquetWriter.flushRowGroup(ParquetWriter.java:221) at org.apache.iceberg.parquet.ParquetWriter.close(ParquetWriter.java:254) at org.apache.iceberg.io.DataWriter.close(DataWriter.java:82) at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.closeCurrent(BaseTaskWriter.java:314) at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.close(BaseTaskWriter.java:341) at org.apache.iceberg.io.UnpartitionedWriter.close(UnpartitionedWriter.java:47) at org.apache.iceberg.io.BaseTaskWriter.complete(BaseTaskWriter.java:96) at io.tabular.iceberg.connect.data.IcebergWriter.flush(IcebergWriter.java:130) at io.tabular.iceberg.connect.data.IcebergWriter.complete(IcebergWriter.java:145) at io.tabular.iceberg.connect.channel.Worker.lambda$receive$2(Worker.java:116) at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) at io.tabular.iceberg.connect.channel.Worker.receive(Worker.java:116) at io.tabular.iceberg.connect.channel.Channel.lambda$consumeAvailable$2(Channel.java:129) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at io.tabular.iceberg.connect.channel.Channel.consumeAvailable(Channel.java:119) at io.tabular.iceberg.connect.channel.Worker.process(Worker.java:105) at io.tabular.iceberg.connect.IcebergSinkTask.processControlEvents(IcebergSinkTask.java:134) at io.tabular.iceberg.connect.IcebergSinkTask.put(IcebergSinkTask.java:121) at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:583) ... 11 more Caused by: java.io.IOException: No space left on device at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method) at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97) at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67) at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74) at java.base/java.nio.channels.Channels.writeFully(Channels.java:96) at java.base/java.nio.channels.Channels$1.write(Channels.java:171) at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:122) at org.apache.iceberg.relocated.com.google.common.io.CountingOutputStream.write(CountingOutputStream.java:54) at org.apache.iceberg.aws.s3.S3OutputStream.write(S3OutputStream.java:201) at java.base/java.io.OutputStream.write(OutputStream.java:127) at org.apache.parquet.io.DelegatingPositionOutputStream.write(DelegatingPositionOutputStream.java:56) at org.apache.parquet.bytes.ConcatenatingByteArrayCollector.writeAllTo(ConcatenatingByteArrayCollector.java:46) at org.apache.parquet.hadoop.ParquetFileWriter.writeColumnChunk(ParquetFileWriter.java:903) at org.apache.parquet.hadoop.ParquetFileWriter.writeColumnChunk(ParquetFileWriter.java:848) at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writeToFileWriter(ColumnChunkPageWriteStore.java:310) at org.apache.parquet.hadoop.ColumnChunkPageWriteStore.flushToFileWriter(ColumnChunkPageWriteStore.java:458) at org.apache.iceberg.parquet.ParquetWriter.flushRowGroup(ParquetWriter.java:213) ... 35 more "`

**Comment by bryanck** [comment]
`S3FileIO` stores temporary files to local disk, by default this will use `java.io.tmpdir` which is likely `/tmp`. If using Strimzi, for example, that mount is very small. You can override the staging file directory by setting `iceberg.catalog.s3.staging-dir`.

**Comment by haripriyarhp** [comment]
Hi, thanks for the suggestion. It works now. :)

**Comment by bryanck** [comment]
It a limitation of the [Strimzi operator](https://github.com/strimzi/strimzi-kafka-operator), I do not believe you can mount volumes on a Kafka Connect container. There have been some issues opened on this, I'd definitely like to see this added. You may want to open one as well or comment on an existing ticket.

For now, try setting `iceberg.catalog.s3.staging-dir` to `/home/kafka/iceberg-staging`.

**Comment by mattssll** [comment]
Here is how you can increase the size of /tmp for a pod
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: strimzi-connect-cluster
  namespace: kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  # Setting up environment variables first
    pod:
      tmpDirSizeLimit: "5Gi"
```
