### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by ayyap-2k** [tabular-io/iceberg-kafka-connect#120]
Hi,
 I am new to this iceberg implementation. I am part of kafka connector platform in my organisation. I would like to know the below details.
1. Is there any way we can get premium support like dedicated support person with defined SLA?
2. Since i am new to this iceberg platform, when we use iceburg kafka connector, where is this iceburg table be created? 
3. I would like to sync the data from kafka topic to s3 iceburg table format.  does this require an iceburg instance in between? 
Kindly clarify.

Thanks.
G. Ayyappan.

**Comment by bryanck** [comment]
Hello,
1. The connector is not yet a managed connector in Confluent, but you could reach out to them to see if they have any options for you. My company (Tabular) can provide premium support, contact bill@tabular.io if interested.
2. Iceberg requires a catalog, and there are various catalog systems you can use, like REST, AWS Glue, Hive, JDBC, etc. Most of the time you'll set the location in your catalog config, e.g. a warehouse location, and tables will be created in this location.
3. As mentioned, you will need a catalog, but Iceberg itself is a library and not a separate server running someplace.

**Comment by bryanck** [comment]
I'm closing this, feel free to open a new ticket for further questions.
