### ISSUE TITLE
Partitioned table not created when auto created is enabled

### ISSUE THREAD

**Issue by haripriyarhp** [tabular-io/iceberg-kafka-connect#123]
Hi, 
I have given the below configs. But the table that is auto created is not partitioned even if the partition-by column is mentioned.  Only a normal table is created.
          iceberg.catalog.catalog-impl: org.apache.iceberg.aws.glue.GlueCatalog
          iceberg.catalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
          iceberg.catalog.s3.staging-dir: /opt/kafka/staging
          iceberg.catalog.warehouse: s3://bucket-name/iceberg
          iceberg.control.commit.interval-ms: 30000
          iceberg.tables: databasename.tablename
          iceberg.table.databasename.tablename.partition-by: id
          iceberg.tables.auto-create-enabled: true
          key.converter: org.apache.kafka.connect.storage.StringConverter
          topics: topic-name
          value.converter: io.confluent.connect.avro.AvroConverter
          value.converter.schema.registry.url: http://localhost:8081
          value.converter.schemas.enable: true
          value.converter.value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

**Comment by haripriyarhp** [comment]
Also in the glue catalog, there is no partition created and also not in the metadata json created for the iceberg.

**Comment by bryanck** [comment]
You may want to check the integration tests and see if those provide any insight. I confirmed the metadata files in my test contained the partition spec.

**Comment by bryanck** [comment]
My only other thought is that the config isn’t getting picked up for the table, if there is a slight mismatch in the name for example.

**Comment by haripriyarhp** [comment]
Hmm... thanks for the prompt reply. Will check the configs once again.

**Comment by bryanck** [comment]
I'm going to close this, feel free to reopen if you have a way to reproduce and I'll look into it.
