### ISSUE TITLE
org.apache.hadoop.security.KerberosAuthException: failure to login

### ISSUE THREAD

**Issue by 13535048320** [tabular-io/iceberg-kafka-connect#125]
Hi.
The following issues were encountered during use:
org. apache. hadoop. security. KerberosAuthException: failure to login: javax. security. auth. login. LoginException: java. lang. NullPointerException: invalid null input: name

Connector settings:
{
  "name": "IcebergSinkConnectorConnector_0",
  "config": {
    "iceberg.catalog.hive.security.authorization": "false",
    "iceberg.hadoop.security.authorization": "false",
    "iceberg.catalog.s3.secret-access-key": "",
    "iceberg.catalog.s3.endpoint": "http://minio:9000",
    "iceberg.catalog.io-impl": "org.apache.iceberg.aws.s3.S3FileIO",
    "iceberg.catalog.client.region": "us-east-1",
    "iceberg.catalog.uri": "thrift://hive:9083",
    "key.converter.schemas.enable": "false",
    "value.converter.schemas.enable": "false",
    "iceberg.catalog.warehouse": "s3a://warehouse",
    "iceberg.catalog.type": "hive",
    "iceberg.catalog.s3.access-key-id": "",
    "name": "IcebergSinkConnectorConnector_0",
    "connector.class": "io.tabular.iceberg.connect.IcebergSinkConnector",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "topics": "hive_demo",
    "iceberg.tables": "demons.demotable",
    "iceberg.catalog": ""
  }
}

**Comment by bryanck** [comment]
This looks like a Hadoop configuration problem to me
