### ISSUE TITLE
one more slash was added on S3 prefix when using iceberg.tables.auto-create-enabled option

### ISSUE THREAD

**Issue by okayhooni** [tabular-io/iceberg-kafka-connect#127]
When I using the connector with `iceberg.tables.auto-create-enabled` option, one more slash was added on S3 prefix like below

if) default db LOCATION of `temp_beta` database : `s3://test_bucket/temp_beta`

- expected S3 path: `s3://test_bucket/temp_beta/test_table/`
- auto-generated S3 path:  `s3://test_bucket/temp_beta//test_table/`

I think it's not intended result unlike https://github.com/tabular-io/iceberg-kafka-connect/issues/118

![image](https://github.com/tabular-io/iceberg-kafka-connect/assets/81631424/8f510f37-95e2-41f5-9768-e43008a7758b)

By the way, is `iceberg.tables.evolve-schema-enabled` option working well..?
If so, how about updating Tabular medium blog for this connector..?
(on `Future enhancements` phrase, it say there is no table schema evolution feature as yet)

https://tabular.medium.com/intro-to-the-iceberg-kafka-connect-sink-f0f86eae2937

**Comment by bryanck** [comment]
I believe this is an issue with Iceberg itself, you may want to raise an issue there. Schema evolution is working and we are currently working on a series of follow-up blog posts to detail some of the new features, so stay tuned.

**Comment by bryanck** [comment]
Thanks for pointing out the outdated docs, I'll update the future enhancements section.

**Comment by bryanck** [comment]
This PR updates the design doc: https://github.com/tabular-io/iceberg-kafka-connect/pull/131

**Comment by okayhooni** [comment]
Thank you @bryanck  !

**Comment by bryanck** [comment]
By the way, there will be a PR in the [Iceberg repo](https://github.com/apache/iceberg/pulls) shortly, to fix the extra slash issue when using the Glue catalog, in case you want to follow along. Thanks for reporting that.
