### ISSUE TITLE
Is there interest in merging some of the features into this project?

### ISSUE THREAD

**Issue by ddcprg** [tabular-io/iceberg-kafka-connect#14]
I built a KC connector for Iceberg

https://github.com/10xfuturetechnologies/kafka-connect-iceberg

I wonder if there is interest in refactoring some of the features of the repo above into this project. For me may be best as I'm not getting loads of support to work on the connector and since tabular is the company supporting Iceberg I rather contribute to this project instead if you are open to accept collaborators.

Apologies for raising this as an issue

**Comment by bryanck** [comment]
We are definitely open to contributors. Feel free to open a PR if there is something in particular you'd like to see added.

**Comment by ddcprg** [comment]
Cool! I'll go through this code and raise issues so I can confirm you are happy with those features before I raise PRs.

Two things come right away to my mind that we'd like in the connector and seem missing are the ability auto create tables and auto evolve the table schema from the Kafka record schemas

**Comment by bryanck** [comment]
Schema evolution is definitely something we want to add. One thing we want to ensure is that there is no data loss, e.g. if a new column is added, we want to immediately start capturing the data for that column across all workers. This will be important especially for CDC use cases. Feel free to ping me on the Iceberg Slack, in the `kafka-connect` channel, we can start a discussion among some others interested in this feature

**Comment by bryanck** [comment]
https://github.com/tabular-io/iceberg-kafka-connect/pull/95 to add schema evolution is up for review if you're interested in giving feedback. It also involved the already-merged https://github.com/tabular-io/iceberg-kafka-connect/pull/93. There will be a couple of quick follow-ups to this once merged, like auto table create and perhaps data type evolution.

**Comment by bryanck** [comment]
I'm going to close this, feel free to open a new ticket if needed. We've proposed moving the sink into the Iceberg project, so if accepted, you can contribute there.
