### ISSUE TITLE
Iceberg Kafka Connect Support For GCP [GCS+Bigquery]

### ISSUE THREAD

**Issue by devorbit** [tabular-io/iceberg-kafka-connect#143]
Hi Team,

I wanted to quickly check if the connector could be used with GCP services like GCS and BigQuery.

I did not see any reference to that, and that got me worried. Also, I consider that BigQuery still doesn't have good support for open table formats and that could be one of the reasons. 

Please share your thoughts.

Thanks
Jay

**Comment by devorbit** [comment]
Thank you @bryanck for quick response. I am facing some issues with the configurations. Can you share some thoughts on these configs?

```
"iceberg.catalog.uri": "http://localhost:19120/api/v1",
"iceberg.catalog.type": "hive"
```

Do I need to supply credentials?

**Comment by bryanck** [comment]
That catalog URI looks suspicious to me, though I haven't used BigLake Metastore before.

**Comment by bryanck** [comment]
It looks like this is being worked on in Iceberg, see this PR: https://github.com/apache/iceberg/pull/7412

**Comment by bryanck** [comment]
I'm going to close this, you can open a ticket in the Iceberg repo, as this is more of an Iceberg concern.
