### ISSUE TITLE
Can't specify truncate or bucket partition transforms

### ISSUE THREAD

**Issue by davidbzhao** [tabular-io/iceberg-kafka-connect#144]
It looks like you're supposed to specify a truncate partition transform like `truncate(col, 10)` [[SchemaUtilsTest](https://github.com/tabular-io/iceberg-kafka-connect/blob/e778e06720cf73a47e8dddb6d852c0e7a0acdad6/kafka-connect/src/test/java/io/tabular/iceberg/connect/data/SchemaUtilsTest.java#L155-L156)], but the `partition-by` configs get [split by comma](https://github.com/tabular-io/iceberg-kafka-connect/blob/e778e06720cf73a47e8dddb6d852c0e7a0acdad6/kafka-connect/src/main/java/io/tabular/iceberg/connect/IcebergSinkConfig.java#L354-L356), meaning my partition string gets parsed as `truncate(col` and `10)`.

**Comment by bryanck** [comment]
Thanks for catching this. I have a [PR](https://github.com/tabular-io/iceberg-kafka-connect/pull/147) up to fix this and will release a new version with the fix once it is merged.

**Comment by davidbzhao** [comment]
Amazing, thanks for the quick change!

**Comment by bryanck** [comment]
This fix is in v0.6.1, feel free to reopen this if it doesn't resolve your issue.
