### ISSUE TITLE
How could I reset source offset safely?

### ISSUE THREAD

**Issue by okayhooni** [tabular-io/iceberg-kafka-connect#150]
On README, there is a section related to this.

[Source topic offsets](https://github.com/tabular-io/iceberg-kafka-connect#source-topic-offsets)
Source topic offsets are stored in two different consumer groups. The first is the sink-managed consumer group defined by the iceberg.control.group-id property. The second is the Kafka Connect managed consumer group which is named connect-<connector name> by default. The sink-managed consumer group is used by the sink to achieve exactly-once processing. The Kafka Connect consumer group is only used as a fallback if the sink-managed consumer group is missing. To reset the offsets, both consumer groups need to be reset.

But, I hope the README contents will be more detailed.

Related questions)

1. Does reset order matter between `sink-managed consumer group` offset and `Kafka Connect managed consumer group` offset? Each order is better to apply reset? (The order don't matter, if the sink connector is STOPPED? )

2. Then, is `total procedure of resetting consuming offset` like below?
- stop sink connector
- reset `sink-managed consumer group` & `Kafka Connect managed consumer group`
- restart sink connector

**Comment by bryanck** [comment]
Yes, you have it right, stop the connector, reset both consumer groups, and restart the connector, the order in which you reset doesn't matter.

**Comment by okayhooni** [comment]
Thanks for quick answer!
