### ISSUE TITLE
 Caused by: org.apache.hadoop.security.KerberosAuthException: failure to login: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name

### ISSUE THREAD

**Issue by NhatDuy11** [tabular-io/iceberg-kafka-connect#160]
I have such an iceberg sink connector configuration :
{
  "name": "IcebergSinkConnectorConnector_currency",
  "config": {
    "iceberg.catalog.s3.endpoint": "http://########",
    "iceberg.catalog.client.region": "us-east-1",
    "iceberg.catalog.s3.path.style.access": "true",
    "iceberg.catalog.s3.aws.credentials.provide": "com.amazonaws.auth.DefaultAWSCredentialsProviderChain",
    "iceberg.catalog.s3.access-key-id": "##################",
    "iceberg.catalog.s3.secret-access-key": "########################",
    "iceberg.catalog.io-impl": "org.apache.iceberg.aws.s3.S3FileIO",
    "iceberg.catalog.uri": "thrift://#########",
    "value.converter.schema.registry.url": "http://schemaregistry.confluent.svc.cluster.local:8081",
    "iceberg.catalog.warehouse": "s3a://######",
    "key.converter.schema.registry.url": "http://schemaregistry.confluent.svc.cluster.local:8081",
    "iceberg.com.amazonaws.services.s3.enableV4": "true",
    "name": "IcebergSinkConnectorConnector_currency",
    "connector.class": "io.tabular.iceberg.connect.IcebergSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "topics": "FBNK_CURRENCY_CDC",
    "iceberg.tables": "cnd.test_currency_cdc",
    "iceberg.tables.auto-create-enabled": "true",
    "iceberg.tables.schema-force-optional": "false",
    "iceberg.tables.evolve-schema-enabled": "true",
    "iceberg.control.topic": "currrency_cdc",
    "iceberg.control.group-id": "currrency_cdc_store",
    "iceberg.connect.group-id": "currrency_cdc"
  }
}
I am using key.convert : String converter I immediately got an error:
Caused by: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
full stack trace error :
<img width="683" alt="Screenshot 2023-11-20 110311" src="https://github.com/tabular-io/iceberg-kafka-connect/assets/90893136/950f86dc-e4c9-44b5-8152-96921ad59d52">
Can someone help me regarding this issue?Thanks guys so much

**Comment by NhatDuy11** [comment]
Hi @bryanck ,Can you help me solve this problem,thanks you.

**Comment by 13535048320** [comment]
@NhatDuy11
#125  Hi NhatDuy11. This is the solution.

**Comment by NhatDuy11** [comment]
@13535048320  thanks you.

**Comment by bryanck** [comment]
This appears to be a dupe of https://github.com/tabular-io/iceberg-kafka-connect/issues/157, see the comments at the bottom of that ticket.
