### ISSUE TITLE
Can't find iceberg-kaka-connect-hive connector on confluent 

### ISSUE THREAD

**Issue by ArkaSarkar19** [tabular-io/iceberg-kafka-connect#221]
Hi Team

There are two distributions that are provided i.e.` iceberg-kafka-connect-runtime` and  `iceberg-kafka-connect-runtime-hive` in the `./kafka-connect-runtime/build/distributions` folder. 
But I can't find the hive connector available on confluent-hub, the only available one one is [https://www.confluent.io/hub/tabular/iceberg-kafka-connect](https://www.confluent.io/hub/tabular/iceberg-kafka-connect), this connector doesn't have the necessary dependencies which are needed for `hive` catalog. 
Can the hive connector be also added to confluent-hub so that it can be installed using `confluent-hub install` command directly ,instead of manually adding the .zip file.

**Comment by tabmatfournier** [comment]
Hello.

Hadoop/Hive have too many security vulnerabilities which are flagged by ConfluentHub's security system which ends up removing the jar, so we no longer publish it there.   It's not a problem with the connector, it's a problem with Hive.

You can go to the releases page (https://github.com/tabular-io/iceberg-kafka-connect/releases) and download the `-HIVE` version and manually upload it as a plugin in Confluent.   E.g. 
![image](https://github.com/tabular-io/iceberg-kafka-connect/assets/160646114/6f21e244-3451-4897-abf0-be2d0c72028d)

**Comment by ArkaSarkar19** [comment]
Hi
Thanks for providing this information.
