### ISSUE TITLE
Source code for iceberg-kafka-connect-runtime-hive-0.6.x

### ISSUE THREAD

**Issue by k0bayash1maru** [tabular-io/iceberg-kafka-connect#222]
Hello team,

Can you please shed some light on this:

From the [release](https://github.com/tabular-io/iceberg-kafka-connect/releases) page, I see that we have 2 version of iceberg-connector one with hive and one without:
- [iceberg-kafka-connect-runtime-0.6.13.zip](https://github.com/tabular-io/iceberg-kafka-connect/releases/download/v0.6.13/iceberg-kafka-connect-runtime-0.6.13.zip)
- [iceberg-kafka-connect-runtime-hive-0.6.13.zip](https://github.com/tabular-io/iceberg-kafka-connect/releases/download/v0.6.13/iceberg-kafka-connect-runtime-hive-0.6.13.zip)

But there  is only one source code(.zip/tgz). If I look at the contents of the source code I see:

![image](https://github.com/tabular-io/iceberg-kafka-connect/assets/51268346/03093d3e-d826-4268-9e20-988d0bca1782)

**Is this the same source code for hive implementation as well ?**

Also the [readme](https://github.com/tabular-io/iceberg-kafka-connect?tab=readme-ov-file#installation) says:

> The zip archive will be found under ./kafka-connect-runtime/build/distributions.

But from the source code, I only see these 2 files:
```
#ls -ltrh
total 16
 src
 build.gradle
#pwd
/iceberg-kafka-connect-0.6.12/kafka-connect-runtime
```

**Am I missing something else ? how do I build the source code ?**

Thanks in advance!

**Comment by tabmatfournier** [comment]
https://github.com/tabular-io/iceberg-kafka-connect/blob/main/kafka-connect-runtime/build.gradle is building the distribution, it bundles up everything.  If you look in `kafka-connect-runtime/src` you'll see there is no code.

**Comment by k0bayash1maru** [comment]
Thank you!
