### ISSUE TITLE
URI support Thrift

### ISSUE THREAD

**Issue by archongum** [tabular-io/iceberg-kafka-connect#27]
Will there be any changes to support hive metastore thrift?
```json
{
    "iceberg.catalog": "org.apache.iceberg.hive.HiveCatalog",
    "iceberg.catalog.name": "default",
    "iceberg.catalog.warehouse": "s3a://warehouse/hive",
    "iceberg.catalog.uri": "thrift://localhost:9083"
}
```

This repo implemented that: https://github.com/getindata/kafka-connect-iceberg-sink#catalogs

**Comment by bryanck** [comment]
Did you run into issues? The catalog config is passed through to Iceberg when initializing the catalog so should work.

The one thing to note is that the default zip distribution does not include the Hive metastore client, so you will need to package that yourself (along with dependencies). The reason why it was excluded is that the Hive client has many transitive dependencies with security vulnerabilities, and this was preventing the connector from being published on Confluent Hub.

I'll work on getting the Hive client included (with security vulnerabilities resolved) so you won't need to package it yourself.

**Comment by archongum** [comment]
> Did you run into issues? 
Yes, some classes not found.

Please let me know when you release a hive-included version.😀

**Comment by archongum** [comment]
I copy a lot of jars to `lib` (maybe some of them is useless) and ClassNotFound fixed. But S3 AccessDenied. 
Should I set access key and secret somewhere like [Confluent S3 Sink](https://docs.confluent.io/kafka-connectors/s3-sink/current/overview.html#credentials-provider-chain) did? 
(BTW, I currently use Confluent S3 Sink to read kafka and write `parquet` file to s3 instead before I've found a sink which can deliver kafka data as iceberg file to s3 directly)

```
Caused by: java.nio.file.AccessDeniedException: s3a://bucket/hive/mars.db/tmp_kafka_iceberg/metadata/00000-678cf05a-3ddf-4e61-aec9-47972f84a9ac.metadata.json: getFileStatus on s3a://bucket/hive/mars.db/tmp_kafka_iceberg/metadata/00000-678cf05a-3ddf-4e61-aec9-47972f84a9ac.metadata.json: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 9MH3THE3AEQGEBH1; S3 Extended Request ID: <id>; Proxy: null), S3 Extended Request ID: <id>:403 Forbidden
```

![image](https://github.com/tabular-io/iceberg-kafka-connect/assets/20929338/292a5287-c69a-4cca-981b-fba8019b6348)

**Comment by bryanck** [comment]
When using the HiveCatalog, the default IO implementation is `HadoopFileIO`. You should switch to using `S3FileIO`. Here is an example config and how you'd set credentials:
```
"iceberg.catalog":"org.apache.iceberg.hive.HiveCatalog",
"iceberg.catalog.uri":"thrift://hive:9083",
"iceberg.catalog.io-impl":"org.apache.iceberg.aws.s3.S3FileIO",
"iceberg.catalog.warehouse":"s3a://bucket/warehouse",
"iceberg.catalog.client.region":"us-east-1",
"iceberg.catalog.s3.access-key-id":"<AWS access>"
"iceberg.catalog.s3.secret-access-key":"<AWS secret>",
```
I have some integration tests on this [branch](https://github.com/tabular-io/iceberg-kafka-connect/tree/hive-integration-tests) using the Hive catalog instead of the REST catalog if you want to see how that's configured. We're working on fleshing out the docs with some more examples and we'll have more info on catalog configuration.

**Comment by archongum** [comment]
> "iceberg.catalog":"org.apache.iceberg.hive.HiveCatalog",
> "iceberg.catalog.uri":"thrift://hive:9083",
> "iceberg.catalog.io-impl":"org.apache.iceberg.aws.s3.S3FileIO",
> "iceberg.catalog.warehouse":"s3a://bucket/warehouse",
> "iceberg.catalog.client.region":"us-east-1",
> "iceberg.catalog.s3.access-key-id":"<AWS access>"
> "iceberg.catalog.s3.secret-access-key":"<AWS secret>",

Did work. Add two more keys: `endpoint` and `path-style-access`.
```
"iceberg.catalog":"org.apache.iceberg.hive.HiveCatalog",
"iceberg.catalog.uri":"thrift://hive:9083",
"iceberg.catalog.io-impl":"org.apache.iceberg.aws.s3.S3FileIO",
"iceberg.catalog.warehouse":"s3a://bucket/warehouse",
"iceberg.catalog.client.region":"us-east-1",
"iceberg.catalog.s3.endpoint": "https://minio.domain.com,
"iceberg.catalog.s3.path-style-access": "true",
"iceberg.catalog.s3.access-key-id":"<AWS access>"
"iceberg.catalog.s3.secret-access-key":"<AWS secret>",
```
