### ISSUE TITLE
Support for Iceberg table properties? regular iceberg maintenance?

### ISSUE THREAD

**Issue by jessiedanwang** [tabular-io/iceberg-kafka-connect#64]
Does it support iceberg table properties such as write mode copy-on-write vs. merge-on-read? And does it manage the S3 file size automatically? in another word, do we need to run regular iceberg maintenance task such as compaction, snapshot expiration and etc.?

**Comment by bryanck** [comment]
The sink supports relevant table properties. Updates are always V2 merge-on-read. You may need to run maintenance depending on your requirements.

**Comment by bryanck** [comment]
Hopefully that answered your question, feel free to open another ticket if you have another question.

**Comment by heman026** [comment]
Is the updates are still Merge-on-read. Any idea will it be made copy-on-write
