### ISSUE TITLE
Connector cannot access worker.properties when using managed connect

### ISSUE THREAD

**Issue by bellemare** [tabular-io/iceberg-kafka-connect#67]
I've been testing this connector on Confluent's managed custom connector service. 

The problem is that the connector is unable to access the worker properties because they are fenced out - the worker properties are entirely Confluent's, and are not accessible by the custom connector. This section fails with permission errors:

https://github.com/tabular-io/iceberg-kafka-connect/blob/b392508260c253d155684bd026bc141698b078b7/kafka-connect/src/main/java/io/tabular/iceberg/connect/IcebergSinkConfig.java#L299

The fix would be to provide the Kafka client configs in connector.properties instead.

**Comment by bryanck** [comment]
You can specify the `iceberg.kafka.*` properties in the sink config if the worker properties can't be accessed.

**Comment by bryanck** [comment]
This was discussed offline, feel free to reopen if this is still an issue.
