### ISSUE TITLE
Record Conversion fails with column value having type `java.util.Date`

### ISSUE THREAD

**Issue by tnweiss** [tabular-io/iceberg-kafka-connect#80]
When the source topic has a Date Column using Kafka's [Date](https://github.com/a0x8o/kafka/blob/master/connect/api/src/main/java/org/apache/kafka/connect/data/Date.java)  connector class

```json
...
{
    "name": "some_date",
    "type": {
        "connector.name": "org.apache.kafka.connect.data.Date",
        "connect.version": 1,
        "logicalType": "date",
        "type": "int"
    }
},
...
```

the connector fails to convert the logical value (`java.util.Date`) into a `LocalDate` resulting in a `RuntimeException` with this message.

```
Cannot convert date:  Mon Dec 13 00:00:00 UTC 2021
```

The `java.util.Date` conversion case is missing from the [convertDateValue](https://github.com/tabular-io/iceberg-kafka-connect/blob/main/kafka-connect/src/main/java/io/tabular/iceberg/connect/data/RecordConverter.java#L307) method.

Adding this, on line 315, seems to resolve the issue.

```java
    } else if (value instanceof Date) {
      return ((Date) value).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
```

**Comment by bryanck** [comment]
Thanks for reporting this, I'll have a fix later today.

**Comment by bryanck** [comment]
Here's the PR for this, which also adds it for the time conversion and adds some missing tests: https://github.com/tabular-io/iceberg-kafka-connect/pull/81

**Comment by bryanck** [comment]
The PR was merged, feel free to reopen if it didn't fix the issue.
